[package]
name = "schannel"
license = "MIT"
version = "0.1.20"
description = "Schannel bindings for Rust, allowing SSL/TLS (e.g. HTTPS) without OpenSSL."
authors = ["Steven Fackler <sfackler@gmail.com>", "Steffen Butzer <steffen.butzer@outlook.com>"]
documentation = "https://docs.rs/schannel"
repository = "https://github.com/steffengy/schannel-rs"
readme = "README.md"
keywords = ["windows", "schannel", "tls", "ssl", "https"]
edition = "2018"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[dependencies]
windows-sys = { version = "0.36", features = [
    "Win32_Foundation", "Win32_Security_Cryptography",
    "Win32_Security_Authentication_Identity", "Win32_Security_Credentials",
    "Win32_System_Memory"] }

[dev-dependencies]
windows-sys = { version = "0.36", features = ["Win32_System_SystemInformation", "Win32_System_Time"] }
